//
//  DatabaseManagerDishes+InitDishesData.m
//  OrderDishes
//
//  Created by 于建峰 on 15/12/15.
//  Copyright © 2015年 yu.jianfeng. All rights reserved.
//

#import "DatabaseManagerDishes+InitDishesData.h"


@implementation DatabaseManagerDishes (InitDishesData)


-(void)addDishes
{
    NSArray *dishesarray = @[
                             [[ModelDishes alloc] initName:@"金牌烤鸭（套）" price:128.0 VIPPrice:118.0 describing:@""],
                             [[ModelDishes alloc] initName:@"标准烤鸭（套）" price:118.0 VIPPrice:108.0 describing:@""],
                             [[ModelDishes alloc] initName:@"标准烤鸭（半套）" price:68.0  VIPPrice:58.0  describing:@""],
                             [[ModelDishes alloc] initName:@"鸭饼" price:6.0   VIPPrice:6.0   describing:@""],
                             [[ModelDishes alloc] initName:@"鸭酱" price:2.0   VIPPrice:2.0   describing:@""],
                             [[ModelDishes alloc] initName:@"葱丝" price:2.0   VIPPrice:2.0   describing:@""],
                             [[ModelDishes alloc] initName:@"瓜条" price:2.0   VIPPrice:2.0   describing:@""],
                             [[ModelDishes alloc] initName:@"鸭架（孜然、椒盐、炖汤）" price:12.0 VIPPrice:12.0 describing:@""],
                             [[ModelDishes alloc] initName:@"麻婆豆腐" price:18.0 VIPPrice:9.0    describing:@"半价菜"],
                             [[ModelDishes alloc] initName:@"蟹黄豆腐" price:56.0 VIPPrice:28.0   describing:@"半价菜"],
                             [[ModelDishes alloc] initName:@"盐菜小肘" price:56.0 VIPPrice:28.0   describing:@"半价菜"],
                             [[ModelDishes alloc] initName:@"文蛤烩丝瓜" price:38.0 VIPPrice:19.0    describing:@"半价菜"],
                             [[ModelDishes alloc] initName:@"蒜茸粉丝蒸扇贝（只）" price:8.0 VIPPrice:8.0 describing:@"特价菜"],
                             [[ModelDishes alloc] initName:@"红烧狮子头（个）" price:8.0 VIPPrice:8.0 describing:@"特价菜"],
                             [[ModelDishes alloc] initName:@"香辣土豆丝" price:18.0 VIPPrice:18.0 describing:@"特价菜"],
                             [[ModelDishes alloc] initName:@"鸭梨拌菜" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"老北京肉皮冻" price:18.0 VIPPrice:15.0 describing:@""],
                             [[ModelDishes alloc] initName:@"花仁菠菜" price:15.0 VIPPrice:12.0 describing:@""],
                             [[ModelDishes alloc] initName:@"黄瓜沾酱（根）" price:4.0 VIPPrice:3.0 describing:@""],
                             [[ModelDishes alloc] initName:@"夫妻肺片" price:35.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"桂花莲藕" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"老醋蛰头" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"招牌素三样" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱香鸭头（只）" price:4.0 VIPPrice:3.0 describing:@""],
                             [[ModelDishes alloc] initName:@"香椿苗拌豆腐丝" price:18.0 VIPPrice:15.0 describing:@""],
                             [[ModelDishes alloc] initName:@"川味凉面" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱香鸡翅" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蛰皮白菜心" price:22.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"水果沙拉" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"口水鸡" price:35.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"老醋花生米" price:9.0 VIPPrice:8.0 describing:@""],
                             [[ModelDishes alloc] initName:@"香椿苗核桃仁" price:28.0 VIPPrice:25.0 describing:@""],
                             [[ModelDishes alloc] initName:@"东北大拉皮" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"川味香肠" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"芥末鸭掌" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"四喜烤麸" price:15.0 VIPPrice:12.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸭梨白切鸡（半只）" price:36.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蓝莓山药" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"风味凉皮" price:18.0 VIPPrice:15.0 describing:@""],
                             [[ModelDishes alloc] initName:@"特色腌黄瓜" price:15.0 VIPPrice:12.0 describing:@""],
                             [[ModelDishes alloc] initName:@"盐水鸭肝" price:25.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"野笋拌猪耳" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"迷你珍菇" price:22.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"爽口西葫芦丝" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"美味留客菜" price:10.0 VIPPrice:9.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱香肘花" price:38.0 VIPPrice:35.0 describing:@""],
                             [[ModelDishes alloc] initName:@"美极小秋耳" price:20.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"招牌吱吱盒" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱香牛肉" price:38.0 VIPPrice:35.0 describing:@""],
                             [[ModelDishes alloc] initName:@"卤水拼盘" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"糟香小黄鱼" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"水晶红果" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"京味烧豆腐" price:18.0 VIPPrice:15.0 describing:@""],
                             [[ModelDishes alloc] initName:@"葱油三脆" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"手撕炝炒圆白菜" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"咸蛋黄焗黄瓜" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"小炒鸡鸭砸" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"石锅南瓜" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"宫保鸡丁" price:20.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"小笼米粉肉" price:42.0 VIPPrice:36.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酥皮虾" price:73.0 VIPPrice:69.0 describing:@""],
                             [[ModelDishes alloc] initName:@"西红柿炖牛腩" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"农家小炒肉" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"肉末豆嘴炒粉条" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸭梨椒麻鸡" price:72.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"风味荞面包" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸡汤木耳" price:18.0 VIPPrice:15.0 describing:@""],
                             [[ModelDishes alloc] initName:@"大碗有机花菜" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"金汤脆笋" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"大碗冬瓜" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"清炒菜尖" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"贝勒爷烤羊肉" price:62.0 VIPPrice:56.0 describing:@""],
                             [[ModelDishes alloc] initName:@"山药木耳" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"红烧肉辣子鸡" price:48.0 VIPPrice:42.0 describing:@""],
                             [[ModelDishes alloc] initName:@"锅包肉" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"钵子豆角" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"剁椒鱼头" price:76.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"双椒鱼头" price:76.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"滑蛋虾仁" price:42.0 VIPPrice:36.0 describing:@""],
                             [[ModelDishes alloc] initName:@"清炒（蒜蓉）西兰花" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"小炒黄牛肉" price:48.0 VIPPrice:42.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蚝油野山菌" price:36.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"东坡肘子" price:88.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"卤耳尖炒香干" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"炒合菜" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鲜花椒炝鱼片" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"一品鲈鱼" price:88.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"水煮肉片（牛肉）" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"口味江团" price:58.0 VIPPrice:56.0 describing:@""],
                             [[ModelDishes alloc] initName:@"石锅江团" price:58.0 VIPPrice:56.0 describing:@""],
                             [[ModelDishes alloc] initName:@"江南小炒" price:36.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"老北京炖吊子" price:68.0 VIPPrice:58.0 describing:@""],
                             [[ModelDishes alloc] initName:@"干炸丸子" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"田园小炒" price:25.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"土豆丝炒粉条" price:18.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"西芹百合" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"口味鸭脖" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"福寿金沙虾" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"铁板牛仔骨" price:88.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"松蘑炖柴鸡" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鲜椒肥牛" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"白灼秋葵" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"坛煨东坡肉" price:78.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"京酱肉丝" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"糖醋里脊" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"香芹鱼丸" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"葱香虾球" price:86.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"宫爆虾球" price:86.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"钵子娃娃菜" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"爆三样" price:48.0 VIPPrice:42.0 describing:@""],
                             [[ModelDishes alloc] initName:@"烧汁四宝" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"馋嘴蛙" price:76.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"海参过油肉" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"芋儿烧排骨" price:48.0 VIPPrice:42.0 describing:@""],
                             [[ModelDishes alloc] initName:@"钵子胡萝卜丝" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"青椒拆骨肉" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"风味毛血旺" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"白灼芥兰" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"竹香烤牛柳" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"风味羊排" price:78.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"山药炖排骨" price:52.0 VIPPrice:46.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鱼香肉丝" price:20.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"葱烧海参" price:88.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酸菜鱼" price:78.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"青椒豆腐炖河鲜" price:52.0 VIPPrice:46.0 describing:@""],
                             [[ModelDishes alloc] initName:@"干锅肥肠" price:52.0 VIPPrice:46.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱爆鱿鱼须" price:46.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"松仁玉米" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"桃仁酱爆鸡丁" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"养生穿心莲" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"石锅牛腩" price:76.0 VIPPrice:68.0 describing:@""],
                             [[ModelDishes alloc] initName:@"麻辣鸭头" price:42.0 VIPPrice:36.0 describing:@""],
                             [[ModelDishes alloc] initName:@"铁板全家福" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"干煸四季豆" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸭血肥肠" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"铁板黑椒牛柳" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"自制石锅豆腐" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸭梨海鲜汇" price:56.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"醋溜木须" price:48.0 VIPPrice:45.0 describing:@""],
                             [[ModelDishes alloc] initName:@"干煸土豆片" price:20.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"老豆腐炖带鱼" price:36.0 VIPPrice:32.0 describing:@""],
                             [[ModelDishes alloc] initName:@"铁板粉丝包菜" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酱香茄子" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"腊八蒜烧肥肠" price:52.0 VIPPrice:46.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鲜虾蒸水蛋" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蒜蓉粉丝蒸生蚝（只）" price:12.0 VIPPrice:10.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蒜蓉粉丝墨鱼花" price:42.0 VIPPrice:38.0 describing:@""],
                             [[ModelDishes alloc] initName:@"梅菜扣肉" price:42.0 VIPPrice:36.0 describing:@""],
                             [[ModelDishes alloc] initName:@"五谷杂粮" price:32.0 VIPPrice:28.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蒜蓉粉丝娃娃菜" price:26.0 VIPPrice:22.0 describing:@""],
                             [[ModelDishes alloc] initName:@"蒜蓉粉丝金针菇" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"清蒸海鲈鱼" price:88.0 VIPPrice:78.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鲈鱼" price:0.0 VIPPrice:0.0 describing:@"牌价"],
                             [[ModelDishes alloc] initName:@"海白虾" price:0.0 VIPPrice:0.0 describing:@"牌价"],
                             [[ModelDishes alloc] initName:@"原汁鲜菌汤" price:52.0 VIPPrice:46.0 describing:@""],
                             [[ModelDishes alloc] initName:@"莲藕炖排骨" price:68.0 VIPPrice:58.0 describing:@""],
                             [[ModelDishes alloc] initName:@"农家土鸡野生菌" price:68.0 VIPPrice:58.0 describing:@""],
                             [[ModelDishes alloc] initName:@"笋干千张煲" price:52.0 VIPPrice:48.0 describing:@""],
                             [[ModelDishes alloc] initName:@"肉松饼" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"鸭梨杂粮饼" price:28.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"炸酱面" price:9.0 VIPPrice:8.0 describing:@""],
                             [[ModelDishes alloc] initName:@"西红柿鸡蛋面" price:9.0 VIPPrice:8.0 describing:@""],
                             [[ModelDishes alloc] initName:@"茄子打卤面" price:9.0 VIPPrice:8.0 describing:@""],
                             [[ModelDishes alloc] initName:@"水饺" price:22.0 VIPPrice:20.0 describing:@""],
                             [[ModelDishes alloc] initName:@"金鸭梨" price:5.0 VIPPrice:4.0 describing:@""],
                             [[ModelDishes alloc] initName:@"葱花饼" price:18.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"糯香黑米糕" price:19.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"武大郎馅饼" price:22.0 VIPPrice:20.0 describing:@""],
                             [[ModelDishes alloc] initName:@"孙姐炒饭" price:22.0 VIPPrice:19.0 describing:@""],
                             [[ModelDishes alloc] initName:@"白米饭" price:2.0 VIPPrice:2.0 describing:@""],
                             [[ModelDishes alloc] initName:@"家常饼" price:15.0 VIPPrice:12.0 describing:@""],
                             [[ModelDishes alloc] initName:@"香芋芝麻卷" price:20.0 VIPPrice:18.0 describing:@""],
                             [[ModelDishes alloc] initName:@"酸辣汤" price:18.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"西红柿鸡蛋汤" price:18.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"疙瘩汤" price:18.0 VIPPrice:16.0 describing:@""],
                             [[ModelDishes alloc] initName:@"湘西手工粉" price:29.0 VIPPrice:26.0 describing:@""],
                             [[ModelDishes alloc] initName:@"妈妈炖菜" price:22.0 VIPPrice:19.0 describing:@""],
                             
                             ];
    
    for (ModelDishes *dishes in dishesarray)
    {
        [self insertDishes:dishes];
    }
}

@end
